models/blog.py
from extensions import db
from sqlalchemy.dialects.postgresql import TSVECTOR


class Blog(db.Model):
    __tablename__ = "blog"

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100))
    url = db.Column(db.String(100))
    description = db.Column(db.String(1000))
    description_token = db.Column(TSVECTOR)

    def __repr__(self):
        return f"Blog({self.id}, {self.title}, {self.url}, {self.description})"

forms/contact.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Length, Email


class ContactForm(FlaskForm):
    username = StringField(
        "Your Name", validators=[DataRequired(), Length(min=2, max=25)]
    )
    email = StringField("Your Email", validators=[DataRequired(), Email()])
    subject = StringField(
        "Subject", validators=[DataRequired(), Length(min=2, max=20)]
    )
    message = TextAreaField("Your Message", validators=[DataRequired()])
    submit = SubmitField("SEND")

    def __repr__(self):
        return f"<Name: {self.username} - Email: {self.email} - Subject: {self.subject}>"

views/blog.py
from flask import Blueprint, render_template, request
from extensions import db
from models.blog import Blog
from app import get_current_year


blog_blueprint = Blueprint("blog", __name__, template_folder="templates")


@blog_blueprint.route("/blog")
def blog():
    """
    View method to render the blog.html page - https://www.abhishekpednekar.com/blog

    Returns
    -------
    blog.html: html / jinja2 template
    """
    page = request.args.get("page", 1, type=int)
    blogs = (
        db.session.query(Blog.id, Blog.title, Blog.url, Blog.description)
        .order_by(Blog.id.desc())
        .paginate(page=page, per_page=7)
    )
    return render_template(
        "blog.html", title="Blog", blogs=blogs, year=get_current_year()
    )

views/contact.py
from flask import Blueprint, flash, redirect, url_for, render_template
from forms.contact import ContactForm
from utilities.tasks import send_email
from app import get_current_year

contact_blueprint = Blueprint("contact", __name__, template_folder="templates")


@contact_blueprint.route("/contact", methods=["GET", "POST"])
def contact():
    """
    View method to render the contact.html page - https://www.abhishekpednekar.com/contact

    Returns
    -------
    contact.html: html / jinja2 template
    """
    form = ContactForm()
    if form.validate_on_submit():
        send_email.delay(
            form.username.data,
            form.email.data,
            form.subject.data,
            form.message.data,
        )
        flash("Thanks! I will be in touch soon.")
        return redirect(url_for("contact.contact"))

    return render_template(
        "contact.html", title="Contact", form=form, year=get_current_year()
    )

views/portfolio.py
from flask import Blueprint, render_template
from app import get_current_year

portfolio_blueprint = Blueprint(
    "portfolio", __name__, template_folder="templates"
)


@portfolio_blueprint.route("/portfolio")
def portfolio():
    """
    View method to render the portfolio.html page - https://www.abhishekpednekar.com/portfolio

    Returns
    -------
    portfolio.html: html / jinja2 template
    """
    return render_template(
        "portfolio.html", title="Portfolio", year=get_current_year()
    )

templates/blog.html
{% extends "layout.html" %}

{% block head %}
{{ super() }}
{% if title %}
<title>My {{ title }}</title>
{% else %}
<title>Abhishek Pednekar</title>
{% endif %}

{% endblock head %}

{% block content %}
<main id="blog">
    <div class="blog-container">
        <h1 class="sm-heading">My blog - <a href="https://codedisciples.in"><span>Code Disciples</span></a></h1>
        <p>Code Disciples is a blog for all things code. The internet is vast and is full of great content and
            mostly
            awesome folks who are always willing to help. However, sometimes, we run into a real head-scratcher
            that
            requires rummaging through heaps of documentation or tutorials and abusing Q&A sites until we hit that
            "eureka!" moment. Most
            blogs on Code Disciples
            stem from such painful moments of frustration. The site provides a means for me to document topics or
            scenarios
            that I struggled with when I first encountered them or subjects that I simply felt would be fun to blog
            about. I hope you find at least some of them to be useful.</p>

        <p>The site is developed with <a href="http://getpelican.com/" target="_blank" rel="noreferrer"><span>Pelican</span></a>
            and deployed using <a href="https://www.netlify.com/" target="_blank" rel="noreferrer"><span>Netlify</span></a>.</p>
        <div class="blog-list">
            {# <h3>Here is a list of all the posts currently on the site:</h3> #}
            <ul>
                {% for blog in blogs.items %}
                <li class="blog{{ loop.index }}" style="list-style: square;">
                    <span>{{ blog.title }}</span><br />
                    <div id="box{{ loop.index }}">
                        <p>{{ blog.description }}</p>
                        <p><a href="{{ blog.url }}" target="_blank" rel="noreferrer"><span>Full article.</span></a></p>
                    </div><br />
                </li>
                {% endfor %}
            </ul>
            {# Pagination #}
            <div class="pagination">
                {% for page_num in blogs.iter_pages() %}
                {% if page_num %}
                <a href="{{ url_for('blog.blog', page=page_num) }}">{{ page_num }}</a>
                {% else %}
                ...
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</main>
<footer class="portfolio-footer main-footer">
    &copy; {{ year }}&nbsp;&nbsp;<b>·</b>&nbsp;&nbsp;Made with <img class="img-footer" alt="footer"
        src="{{ url_for('static', filename='images/love.ico') }}"> in
    Bangalore
</footer>
<script
  src="https://code.jquery.com/jquery-3.4.1.js"
  integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
  crossorigin="anonymous"></script>

<script type=" text/javascript" src=" {{ url_for('static', filename='js/blog.js') }}"></script>
{% endblock content %}

templates/contact.html
{% extends "layout.html" %}

{% block head %}
{{ super() }}
{% if title %}
<title>{{ title }} Me</title>
{% else %}
<title>Abhishek Pednekar</title>
{% endif %}

{% endblock head %}

{% block content %}
<main id="contact">
    <div id="wrapper">
        <div id="left">

            {% with messages = get_flashed_messages() %}
            {% if messages %}
            {% for message in messages %}
            <div class="alert-success">
                {{ message }}
            </div>
            {% endfor%}
            {% endif %}
            {% endwith%}

            <h1 class="sm-heading">
                Contact <span class="text-secondary">Me</span>
            </h1>
            <div id="contact-form">
                <form method="POST" , action="">
                    {{ form.hidden_tag() }}
                    <div>
                        {{ form.username.label(class="text-label") }}

                        {% if form.username.errors %}
                        {{ form.username(class="text-input text-error") }}
                        <div class="error-message">
                            {% for error in form.username.errors %}
                            <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                        {% else %}
                        {{ form.username(class="text-input") }}
                        {% endif %}
                    </div>
                    <div>
                        {{ form.email.label(class="text-label") }}
                        {% if form.email.errors %}
                        {{ form.email(class="text-input text-error") }}
                        <div class="error-message">
                            {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                        {% else %}
                        {{ form.email(class="text-input") }}
                        {% endif %}
                    </div>
                    <div>
                        {{ form.subject.label(class="text-label") }}
                        {% if form.subject.errors %}
                        {{ form.subject(class="text-input text-error") }}
                        <div class="error-message">
                            {% for error in form.subject.errors %}
                            <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                        {% else %}
                        {{ form.subject(class="text-input") }}
                        {% endif %}
                    </div>
                    <div>
                        {{ form.message.label(class="text-label") }}
                        {% if form.message.errors %}
                        {{ form.message(class="text-area-input text-error") }}
                        <div class="error-message">
                            {% for error in form.message.errors %}
                            <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                        {% else %}
                        {{ form.message(class="text-area-input") }}
                        {% endif %}
                    </div>
                    <div>
                        {{ form.submit(class="contact-btn") }}
                    </div>
                </form>
            </div>

        </div>

        <div id="right">
            <h1 class="sm-heading">References</h1>
            <div id="books">
                <h4>Books</h4>
                <div class="books-top">
                    <a target="_blank" rel="noreferrer"
                        href="https://www.amazon.in/Python-Tricks-Buffet-Awesome-Features/dp/1775093301/ref=sr_1_3?keywords=python+tricks&qid=1564645926&s=gateway&sr=8-3">
                        <img alt="book" class="book-widget"
                            src="https://images-na.ssl-images-amazon.com/images/I/41Shl3kYpsL._SX331_BO1,204,203,200_.jpg">
                    </a>

                    <a target="_blank" rel="noreferrer"
                        href="https://www.amazon.in/Automate-Boring-Python-Albert-Sweigart/dp/1593275994/ref=sr_1_2?crid=1FFWYK9DHGM3S&keywords=automate+the+boring+stuff+with+python&qid=1564648939&s=gateway&sprefix=automate%2Caps%2C298&sr=8-2">
                        <img alt="book" class="book-widget"
                            src="https://images-na.ssl-images-amazon.com/images/I/915d%2BqI9NAL.jpg">
                    </a>
                </div>

                <div class="books-center">
                    <a target="_blank" rel="noreferrer"
                        href="https://www.amazon.in/Cracking-Coding-Interview-Programing-Questions/dp/0984782850/ref=sr_1_1?crid=2LM4CO6RWHVV2&keywords=cracking+the+coding+interview+python&qid=1564650340&s=gateway&sprefix=cracking+the+coding+interview+pyth%2Caps%2C313&sr=8-1">
                        <img alt="book" class="book-widget" src="https://images-na.ssl-images-amazon.com/images/I/71jRvBEDNmL.jpg">
                    </a>

                    <a target="_blank" rel="noreferrer"
                        href="https://www.amazon.in/Python-Programming-modular-approach-Pearson/dp/9332585342/ref=sr_1_5?keywords=python+programming&qid=1564650647&s=gateway&sr=8-5">
                        <img alt="book" class="book-widget"
                            src="https://images-na.ssl-images-amazon.com/images/I/51zt8KcbCDL._SX364_BO1,204,203,200_.jpg">
                    </a>
                </div>

                <div class="books-bottom">
                    <a target="_blank" rel="noreferrer"
                        href="https://www.amazon.in/Pragmatic-Programmer-Andrew-Hunt/dp/8131722422/ref=sr_1_1?crid=35ZPWP5MYCTF7&keywords=the+pragmatic+programmer&qid=1564651347&s=gateway&sprefix=the+pragma%2Caps%2C281&sr=8-1">
                        <img alt="book" class="book-widget"
                            src="https://images-na.ssl-images-amazon.com/images/I/4163oCmhq%2BL._SX425_BO1,204,203,200_.jpg">
                    </a>
                    <a target="_blank" rel="noreferrer"
                        href="https://www.amazon.in/Flask-Web-Development-Miquel-Grinberg/dp/1491991739/ref=sr_1_15?keywords=flask+programming&qid=1564651582&s=gateway&sr=8-15">
                        <img alt="book" class="book-widget"
                            src="https://images-na.ssl-images-amazon.com/images/I/514Lbvt36zL._SX377_BO1,204,203,200_.jpg">
                    </a>
                </div>
            </div>
            <hr>
            <div id="pod-yt">
                <div id="podcasts">
                    <h4>Podcasts</h4>
                    <div class="pod-list">
                        <a target="_blank" rel="noreferrer" href="https://talkpython.fm/">Talk Python To Me</a><br>
                        <a target="_blank" rel="noreferrer" href="https://pythonbytes.fm/">Python Bytes</a><br>
                        <a target="_blank" rel="noreferrer" href="https://testandcode.com">Test & Code</a><br>
                    </div>
                </div>
                <div id="channels">
                    <h4>YouTube</h4>
                    <div class="channel-list">
                        <a target="_blank" rel="noreferrer" href="https://www.youtube.com/channel/UCCezIgC97PvUuR4_gbFUs5g">Corey
                            Schafer</a><br>
                        <a target="_blank" rel="noreferrer" href="https://www.youtube.com/channel/UC29ju8bIPH5as8OGnQzwJyA">Traversy
                            Media</a><br>
                        <a target="_blank" rel="noreferrer" href="https://www.youtube.com/channel/UCI0vQvr9aFn27yR6Ej6n5UA">Real
                            Python</a><br>
                    </div>
                </div>
            </div>
</main>
<footer class="portfolio-footer main-footer">
    &copy; {{ year }}&nbsp;&nbsp;<b>·</b>&nbsp;&nbsp;Made with <img class="img-footer" alt="footer"
        src="{{ url_for('static', filename='images/love.ico') }}"> in
    Bangalore
</footer>
<script type="text/javascript" src=" {{ url_for('static', filename='js/contact.js') }}"></script>
{% endblock content %}

templates/home.html
{% extends "layout.html"%}

{% block head %}
{{ super() }}
<title>Abhishek Pednekar</title>
{% endblock head %}

{% block content %}
<main id="home">
    <h1 class="lg-heading">
        Abhishek <span class="text-secondary">Pednekar</span>
    </h1>
    <h2 class="sm-heading">
        Web Developer & Programmer
    </h2>
    <div class="icons">
        <a href="https://github.com/AbhishekPednekar84" target="_blank" rel="noreferrer">
            <i class="fab fa-github fa-2x"></i>
        </a>
        <a href="https://www.linkedin.com/in/abhishekpednekar84" target="_blank" rel="noreferrer">
            <i class="fab fa-linkedin fa-2x"></i>
        </a>
        <a href="{{ url_for('contact.contact') }}">
            <i class="fas fa-envelope fa-2x"></i>
        </a>
    </div>
</main>
{% endblock  content %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block head %}
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-145611420-2"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-145611420-2');
    </script>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta itemprop="givenName" itemscope itemtype="https://schema.org/Person" name="Description" content="Abhishek Pednekar's portfolio site">
    <link rel="shortcut icon" href="{{ url_for('static', filename='images/A.png') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='scss/main.css') }}">
    <!-- <script src="https://kit.fontawesome.com/5ceb4d3475.js"></script> -->
    {% endblock head %}
</head>

<body id="bg-img">
    <header>
        <div class="menu-btn">
            <div class="btn-line"></div>
            <div class="btn-line"></div>
            <div class="btn-line"></div>
        </div>

        <nav class="menu">
            <div class="menu-branding">
                <div class="potrait">

                </div>
            </div>
            <ul class="menu-nav">
                <li class="nav-item current">
                    <a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('portfolio.portfolio') }}">Portfolio</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('blog.blog') }}">Blog</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('contact.contact') }}">Contact Me</a>
                </li>
            </ul>
        </nav>
    </header>

    {% block content %}
    {% endblock content %}

    <script type="text/javascript" src="{{ url_for('static', filename='js/main.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/all.js') }}"></script>
</body>

</html>

templates/portfolio.html
{% extends "layout.html" %} {% block head %} {{ super() }} {% if title %}
<title>My {{ title }}</title>
{% else %}
<title>Abhishek Pednekar</title>
{% endif %} {% endblock head %} {% block content %}
<main id="portfolio">
  <h1 class="sm-heading">
    About
    <span class="text-secondary">Me</span>
  </h1>
  <!-- Grid -->
  <div class="about-info">
    <div class="bio-img-cv">
      <div>
        <img
          src="{{ url_for('static', filename='images/profile.jpg') }}"
          alt="Abhishek Pednekar"
          class="bio-image"
        />
      </div>
      <div class="bio-cv-div">
        <a
          href="{{ url_for('static', filename='cv/Abhishek_Pednekar.pdf') }}"
          target="_blank"
          class="btn-cv"
        >
          <i class="fas fa-eye"></i>
          &nbsp;&nbsp;View my CV
        </a>
      </div>
    </div>

    <div class="bio">
      <h3 class="text-secondary">BIO</h3>
      <p>
        Hands-on, result-oriented and highly motivated application developer and
        programmer. I have worked with and mentored cross-functional teams of
        varying sizes across geographical locations. For me, user experience and
        customer satisfaction are paramount and I, therefore always strive to
        deliver feature-rich, user-friendly, responsive and visually appealing
        applications.
      </p>
    </div>

    <div class="job job-1">
      <h3 class="sm-heading" style="text-align: center;">Skills</h3>
      <div class="bar-container">
        <div class="bar-lang">HTML</div>
        <div class="bar-fill" style="width: 60%;"></div>
        <div class="bar-pct" style="width: 15%;">90%</div>
      </div>
      <div class="bar-container">
        <div class="bar-lang">CSS</div>
        <div class="bar-fill" style="width: 50%;"></div>
        <div class="bar-pct" style="width: 25%;">80%</div>
      </div>
      <div class="bar-container">
        <div class="bar-lang">Python</div>
        <div class="bar-fill" style="width: 50%;"></div>
        <div class="bar-pct" style="width: 25%;">80%</div>
      </div>
      <div class="bar-container">
        <div class="bar-lang">JavaScript</div>
        <div class="bar-fill" style="width: 35%;"></div>
        <div class="bar-pct" style="width: 40%;">60%</div>
      </div>
      <div class="bar-container">
        <div class="bar-lang">Flask</div>
        <div class="bar-fill" style="width: 50%;"></div>
        <div class="bar-pct" style="width: 25%;">80%</div>
      </div>
      <div class="bar-container">
        <div class="bar-lang">Django</div>
        <div class="bar-fill" style="width: 45%;"></div>
        <div class="bar-pct" style="width: 30%;">70%</div>
      </div>
      <div class="bar-container">
        <div class="bar-lang">Git</div>
        <div class="bar-fill" style="width: 55%;"></div>
        <div class="bar-pct" style="width: 20%;">85%</div>
      </div>
      <div class="bar-container">
        <div class="bar-lang">C#</div>
        <div class="bar-fill" style="width: 35%;"></div>
        <div class="bar-pct" style="width: 40%;">60%</div>
      </div>
      <div class="bar-container">
        <div class="bar-lang">React.js</div>
        <div class="bar-fill" style="width: 40%;"></div>
        <div class="bar-pct" style="width: 35%;">65%</div>
      </div>
      <div class="bar-container">
        <div class="bar-lang">SQL</div>
        <div class="bar-fill" style="width: 55%;"></div>
        <div class="bar-pct" style="width: 20%;">85%</div>
      </div>
    </div>

    <div class="job job-3">
      <h3 class="sm-heading" style="text-align: center;">
        Sites Developed and Maintained by Me
      </h3>
      <div class="personal-site">
        <ul>
          <li class="personal-site-list">
            <a href="https://kar.covid19-info.website">
              Kar.COVID19-Info.website
            </a>
            <p>
              An unofficial COVID 19 tracker created with React.js for the state
              of Karnataka.
              <a
                href="https://github.com/AbhishekPednekar84/personal-portfolio"
                target="_blank"
                rel="noreferrer"
              >
                View
              </a>
              the repository on Github.
            </p>
          </li>
          <li class="personal-site-list">
            <a href="https://yahpq.rocks">YAHPQ.rocks</a>
            <p>
              A quiz site created with a React.js, PostgreSQL and Django REST
              API. The site is deployed on a Digital Ocean droplet.
              <a
                href="https://github.com/AbhishekPednekar84/hpquiz-frontend"
                target="_blank"
                rel="noreferrer"
              >
                View
              </a>
              the repository on Github.
            </p>
          </li>
          <li class="personal-site-list">
            <a href="https://coronamythbusters.com">CoronaMythBusters.com</a>
            <p>
              A COVID-19 awareness site created in Django, HTML, CSS, jQuery,
              Redis and PostgreSQL. The site is deployed on a Digital Ocean
              droplet.
              <a
                href="https://github.com/AbhishekPednekar84/project-covid19"
                target="_blank"
                rel="noreferrer"
              >
                View
              </a>
              the repository on Github.
            </p>
          </li>
          <li class="personal-site-list">
            <a href="https://abhishekpednekar.com">AbhishekPednekar.com</a>
            <p>
              Personal portfolio site developed using Flask, HTML, Sass, jQuery,
              Redis and PostgreSQL. Site deployed on a Digital Ocean droplet.
              <a
                href="https://github.com/AbhishekPednekar84/personal-portfolio"
                target="_blank"
                rel="noreferrer"
              >
                View
              </a>
              the repository on Github.
            </p>
          </li>
          <li class="personal-site-list">
            <a href="https://codedisciples.in" target="_blank" rel="noreferrer">
              CodeDisciples.in
            </a>
            <p>
              Personal blog site developed in Pelican, HTML, CSS and Markdown.
              Site deployed using Netlify. Includes a Flask
              <a
                href="https://github.com/AbhishekPednekar84/personal-portfolio/tree/portfolio-page-updates/api"
              >
                REST API
              </a>
              with full-text search.
              <a
                href="https://github.com/AbhishekPednekar84/personal-blog-site"
                target="_blank"
                rel="noreferrer"
              >
                View
              </a>
              the repository on Github.
            </p>
          </li>
        </ul>
      </div>
    </div>
  </div>
</main>
<footer class="portfolio-footer main-footer">
  &copy; {{ year }}&nbsp;&nbsp;
  <b>·</b>
  &nbsp;&nbsp;Made with
  <img
    class="img-footer"
    alt="footer"
    src="{{ url_for('static', filename='images/love.ico') }}"
  />
  in Bangalore
</footer>

<script
  type="text/javascript"
  src="{{ url_for('static', filename='js/portfolio.js') }}"
></script>
{% endblock content %}